### ISSUE TITLE
Understand how to crawl a web page using Python

### ISSUE THREAD

**Issue by M-Shan** [M-Shan/tech-crunchers#6]
the purpose of this task or issue is to understand how you can access a website in python script.

following points need to be taken care in this task:

- how to send url request via python script
- how to grab data recieved from url request
- how to conveniently parse the data and extract relevant information

this task does not expect any scripts to be added in the repository but the expectation will be that you understand how you can retrieve and access data from www.

**Comment by M-Shan** [comment]
@Raspberry-beans please update

**Comment by Raspberry-beans** [comment]
@M-Shan I am working on this issue. I will update you as early as possible. 
Thanks!

**Comment by M-Shan** [comment]
> @M-Shan I am working on this issue. I will update you as early as possible. 
> Thanks!

@Raspberry-beans ok.
